name: Build and Push Docker Images

on:
  workflow_dispatch: # May change to 'push' later..

jobs:
  # Based on https://github.com/marketplace/actions/build-and-push-docker-images
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: anickfischer
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push builder image
        uses: docker/build-push-action@v3
        with:
          push: true
          file: Dockerfile.builder
          tags: "anickfischer/clei:latest-builder"

      - name: Build and push base image
        uses: docker/build-push-action@v3
        with:
          push: true
          file: Dockerfile.base
          tags: "anickfischer/clei:latest"