name: Build and Push Docker Images

on:
  workflow_dispatch: # May change to 'push' later..

env:
  BUILDER_IMAGE_NAME: "anickfischer/clei:latest-builder"
  BASE_IMAGE_NAME: "anickfischer/clei:latest"

jobs:
  # Based on https://github.com/marketplace/actions/build-and-push-docker-images
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: anickfischer
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build builder image
        uses: docker/build-push-action@v3
        with:
          load: true
          file: Dockerfile.builder
          tags: ${{ env.BUILDER_IMAGE_NAME }}

      - name: Build base image
        uses: docker/build-push-action@v3
        with:
          load: true
          file: Dockerfile.base
          tags: ${{ env.BASE_IMAGE_NAME }}

      - name: Scan builder image
        uses: azure/container-scan@v0.1
        with:
          image-name: ${{ env.BUILDER_IMAGE_NAME }}

      - name: Scan base image
        uses: azure/container-scan@v0.1
        with:
          image-name: ${{ env.BASE_IMAGE_NAME }}

      - name: Push builder image
        uses: docker/build-push-action@v3
        with:
          push: true
          file: Dockerfile.builder
          tags: ${{ env.BUILDER_IMAGE_NAME }}

      - name: Push base image
        uses: docker/build-push-action@v3
        with:
          push: true
          file: Dockerfile.base
          tags: ${{ env.BASE_IMAGE_NAME }}